### PR TITLE
Responsive update

### PR DESCRIPTION
**Pull request by jmather**
Made it the slider work for a fully responsive / fluid design.

Added responsiveSlideContainerHeight option to control forced container resizing.

Added Example #9 for use-case.

### CODE REVIEW

**Comment by ColColonCleaner** [comment]
Were you running into a problem with height:100% or height:inherit not working in your css? I'm working on an app that dynamically changes both height and width, and have never run into a height issue.

As long as you have your css correct, this shouldn't be needed.

Please explain your premise.

**Comment by jmather** [comment]
The example I built for the changes is the use-case that I had trouble with.

Problems I ran into:

1) When the page was loaded smaller, and then made wider, the slider was stuck at whatever the start width was as a max.

2) Heights behaved very very strangely if they were not explicitly defined on the container, which prevented the navigation from moving with it.

If you pull my tag and look at example 9, you will see the over-all effect that I was going for, and could not achieve without these fixes.

Thanks!

**Comment by iosscripts** [comment]
Hi @jmather. 

> 1) When the page was loaded smaller, and then made wider, the slider was stuck at whatever the start width was as a max.

What browser/hardware are you seeing the width issues on? I am having issues reproducing it in my version :(

**Comment by jmather** [comment]
Chrome on OSX. This video example uses origin/master's iosslider w/ Example #9 (so you can reproduce, hopefully).

http://www.youtube.com/watch?v=sJYG5XjkMOw

It shows both the height issue (when not explicitly defined in the css), and the width issue (when refreshed small and then resized to wide).

Hopefully this makes it more clear.

I tried to made the modifications to the code as simple as possible as well. I wasn't sure if your height behavior was intended or not though, which is why I handled it the way I did (conditionally skipping the forced height).

Thanks!

**Comment by iosscripts** [comment]
Not sure I like this approach actually. Your example only applies when images are contained within the slides because they maintain their own aspect ratios. 

I will still maintain that a height on the iosSlider div and a width must be defined on the slides. This is the most effective way to guarantee that the maximum amount of possible implementations of this script will work.

I have created a new demo in _demos/_examples/9-Full-Width-Responsive-Height/. It uses the padding-bottom % container method to achieve a responsive height across all implementations. Test with the latest v1.0.29, I have made a modification to the height calculation. 

Let me know what you think.

**Pull request closed without merging**
