### PR TITLE
improvements

### PR DESCRIPTION
**Pull request by samuelbirch**
removed the webkit css as mentioned in issue #59

also improved the vertical page scrolling detection.

### CODE REVIEW

**Comment by marcwhitbread** [comment]
I like your enthusiasm. I will be running some tests on your code to make sure it's on the level before I do anything. Then I will look at manually making the additions, I have a few new changes to commit from my end as well.

**Comment by samuelbirch** [comment]
thats cool, i was asked to look at a few iPad performance issues on a project that uses this plugin. Good work by the way - its a nice plugin.

I was also thinking it might be good to store the vertical & horizontal detection offsets (current 5px) in a variable or as a param. Then users can tweak when the slide etc kicks in. - just a thought?

**Comment by marcwhitbread** [comment]
Good idea. I'll create a new issue to remind myself to do it.

**Comment by iosscripts** [comment]
I have manually added the pull request to v1.0.20.

**Pull request closed without merging**
